### ISSUE TITLE
How to start a bot?

### ISSUE THREAD

**Issue by port24** [tegal1337/YOMEN#10]
Friend tell me how to run the bot? what modules or what is needed only step by step thanks in advance!

**Comment by port24** [comment]
here is what i get : npm install >>> - reify:puppeteer: WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest

**Comment by fdciabdul** [comment]
what nodejs version are you using?

**Comment by port24** [comment]
> what nodejs version are you using?

Windows (x64) 18.1.0

**Comment by fdciabdul** [comment]
> > what nodejs version are you using?
> 
> Windows (x64) 18.1.0

download visual studio build tools 2019 ,  and   install dekstop development with c++

**Comment by port24** [comment]
> > > what nodejs version are you using?
> > 
> > 
> > Windows (x64) 18.1.0
> 
> download visual studio build tools 2019 , and install dekstop development with c++

Thanks everything worked!

_Can you tell me how to make the bot search for videos not from the top, but which were uploaded in the last hour._

**Comment by port24** [comment]
How to force a bot to skip a live broadcast. It's very necessary
After a failure, the bot turns off (((

Something Wrong maybe this is Short videos , live stream , or broken error : TimeoutError: waiting for selector `yt-formatted-string[id='content-text']` failed: timeout 30000ms exceeded

**Comment by port24** [comment]
copycomment:true, // false if you want use comment above , i mean from array
false no work

**Comment by port24** [comment]
If there is at least one comment under the video, then the bot works well, but as soon as the bot enters the video where there are no comments, it immediately crashes. 

Can someone help with this bug?

**Comment by fdciabdul** [comment]
> If there is at least one comment under the video, then the bot works well, but as soon as the bot enters the video where there are no comments, it immediately crashes.
> 
> Can someone help with this bug?

Can you  send the error ? Or sample video when the bot getting an error ?

**Comment by port24** [comment]
> > If there is at least one comment under the video, then the bot works well, but as soon as the bot enters the video where there are no comments, it immediately crashes.
> > Can someone help with this bug?
> 
> Can you send the error ? Or sample video when the bot getting an error ?

https://www.youtube.com/watch?v=b1Sxov23yMg

Here on the first video, he does not want to leave a comment under this video, because there are no others. On another video, he writes a comment without problems, since there are already other comments

**Only this time the bot doesn't crash, it just skips the video**

**Comment by port24** [comment]
bot writes to console  "So.. we need collecting those comment , so we can copy that"

Only I can’t understand why the bot is copying someone else’s comment if I disabled the implementation of the function

  trending: false,
  copycomment:**false**, // false if you want use comment above , i mean from array
  multiakun: false, // true if you want to you multiple account

**Comment by port24** [comment]
**Will this bug be fixed?**

**Comment by fdciabdul** [comment]
> **Will this bug be fixed?**

this has been fixed in new version , clone again and you'll feel the change

**Comment by port24** [comment]
> > **Will this bug be fixed?**
> 
> this has been fixed in new version , clone again and you'll feel the change

Thank you I will check now
