### ISSUE TITLE
Something Wrong maybe this is Short videos , live stream , or broken error : TypeError: manualComment.manualComment is not a function

### ISSUE THREAD

**Issue by poealone** [tegal1337/YOMEN#21]
Something Wrong maybe this is Short videos , live stream , or broken error : TypeError: manualComment.manualComment is not a function

Keep getting this error when i try to use manual comments, anyone else getting this issue?

**Comment by fdciabdul** [comment]
fixed [#291](https://github.com/tegal1337/YOMEN/commit/2913bfbaab4bcf2598cef14cbb27c5933693165b)
