### ISSUE TITLE
get bug like this

### ISSUE THREAD

**Issue by lordmen99** [tegal1337/YOMEN#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Something Wrong maybe this is Short videos , live stream , or broken error : TimeoutError: waiting for selector `#simplebox-placeholder` failed

**Comment by fdciabdul** [comment]
seems like youtube change thei UI , i will try to fix this
