### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by hghfs111** [tegal1337/YOMEN#29]
Everything works but it doesnt click on add a comment i have to manually do it

**Comment by fdciabdul** [comment]
let mee see it and fix it fast as possible , thanks for the report :)

**Comment by FisherWL** [comment]
have the paid version fixed this?

**Comment by SarbagyaKha** [comment]
> have the paid version fixed this?

How do you even run this?

**Comment by fdciabdul** [comment]
@hghfs111 @SarbagyaKha i've been fixed this bug

**Comment by fdciabdul** [comment]
@FisherWL there's no paid version , i just made GUI Version but with license .. you can send any amount to my paypal https://paypal.me/fdciabdul and send your email inside it , it automatically give you license 

the GUI version is more easy to use rather than this

**Comment by fdciabdul** [comment]
@FisherWL and you can get live support with me
