### ISSUE TITLE
Chrome not installed in program Files

### ISSUE THREAD

**Issue by steverob1066** [tegal1337/YOMEN#33]
I updated this installation but now the program can't find Chrome:
"Could not find Google Chrome executable for channel 'chrome' at 'C:\Program Files\Google\Chrome\Application\chrome.exe'.

This is because Chrome is in Program Files (x86) which is currently the deefault location according to Google.

**Comment by fdciabdul** [comment]
> I updated this installation but now the program can't find Chrome: "Could not find Google Chrome executable for channel 'chrome' at 'C:\Program Files\Google\Chrome\Application\chrome.exe'.
> 
> This is because Chrome is in Program Files (x86) which is currently the deefault location according to Google.

i know this error , i will try to fix it
