### ISSUE TITLE
ERROR USING AUTO COMMENT FROM CHAT GPT 

### ISSUE THREAD

**Issue by aljawary** [tegal1337/YOMEN#37]
here is the log
[errorCommenting.log](https://github.com/tegal1337/YOMEN/files/11327584/errorCommenting.log)

and the console image
![Screenshot_1](https://user-images.githubusercontent.com/43963987/234430696-6128e211-91c7-4707-80c7-8dccdf75212d.png)

**Comment by fdciabdul** [comment]
hello this is issue have been fixed , you can try in a new update
