### ISSUE TITLE
delay in config

### ISSUE THREAD

**Issue by mbfakourii** [tegal1337/YOMEN#40]
in [this ](https://github.com/tegal1337/YOMEN/blob/0a2c4e680905bc1a74b710f13dc4181cf518ef7c/main.js#LL307C14-L307C14)line 

use ```delay``` Isn't it better to add it to the config file?

@tegal1337

**Comment by fdciabdul** [comment]
Oh I forgot to add it

**Comment by fdciabdul** [comment]
PR open @mbfakourii
