### ISSUE TITLE
YT BOT

### ISSUE THREAD

**Issue by 420stoned** [tegal1337/YOMEN#43]
Hey i wrote you on YT. I got the bot running now.

It logs into google account and opens yt. but when it trys to make a comment there is an "error" 401.

Cannot create comment!
Error: Request failed with status code 401

**Comment by fdciabdul** [comment]
u should change the config for AI Comment to false

https://github.com/tegal1337/YOMEN/blob/53bd382678569158833d8fce0498d18e6f1ebe82/config.js#L10

**Comment by 420stoned** [comment]
⠙ Thank you <3
✓ done..
⠹ Thank you <3
✓ done..

Thought it because of that. There is a scammer company i want to spam with facts about them. Thats why i asked.
Thank you !
